# Generated by Django 4.0.3 on 2022-03-17 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=150)),
                ('staff', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scrapbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('state', models.TextField()),
                ('date', models.DateField()),
                ('destination', models.TextField()),
                ('favorite_foodstop', models.TextField()),
                ('soundtrack', models.TextField()),
                ('favorite_experience', models.TextField()),
                ('other_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scrapbook_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrapbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shotgunapi.scrapbook')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shotgunapi.tag')),
            ],
        ),
        migrations.AddField(
            model_name='scrapbook',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='shotgunapi.Scrapbook_Tag', to='shotgunapi.tag'),
        ),
        migrations.AddField(
            model_name='scrapbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shotgunapi.app_users'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('scrapbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapbooks', to='shotgunapi.scrapbook')),
            ],
        ),
    ]
