# Generated by Django 4.0.3 on 2022-03-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shotgunapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shotgunapi.app_users'),
        ),
    ]
