# Generated by Django 4.0.3 on 2022-03-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotgunapi', '0002_alter_scrapbook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbook',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='shotgunapi.Scrapbook_Tag', to='shotgunapi.tag'),
        ),
    ]
